name: Geuze Bot

on:
  push:
    branches: [main]

env:
  DOCKER_HOST: ghcr.io
  DOCKER_USER: andregeuze
  IMAGE_NAME: geuzedevopsagent
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: What is our purpose
        run: |
          echo ${{ github.workspace }}
          echo ${{ github.ref }}
          echo ${{ github.workflow }}
          echo ${{ github.event_name }}
          echo ${GITHUB_SHA}
      - name: Build the Docker image
        run: |
          docker build . \
            --tag ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:1.0-latest \
            --tag ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:$(date +'%Y%m%d.%H%M%S')-preview

      - name: Push image to Github Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.DOCKER_HOST }} -u ${{ env.DOCKER_USER }} --password-stdin
          docker push --all-tags ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}

      # - name: Cleanup old images in ACR
      #   uses: Azure/cli@v1
      #   continue-on-error: true
      #   with:
      #     azcliversion: 2.30.0
      #     # Specify the script here
      #     inlineScript: |
      #       az login --service-principal -u "${{ secrets.AZURE_USER }}" -p "${{ secrets.AZURE_PASSWORD }}" -t "geuze.onmicrosoft.com"
      #       az acr run --registry "${{ env.ACR_USER }}" --cmd "acr purge --filter '${{ env.IMAGE_NAME }}:.*-preview' --ago 24h" /dev/null

      # - name: Push the Docker image to ACR
      #   if: ${{ github.event_name == 'push' }} # Only do it when building on main merge
      #   run: |
      #     echo "${{ secrets.GEUZECONTAINERS_PASSWORD }}" | docker login -u "${{ env.ACR_USER }}" --password-stdin ${{ env.ACR_HOST }}
      #     docker push --all-tags ${{ env.ACR_HOST }}/${{ env.IMAGE_NAME }}